# Classifying Penguins with Keras

In [14]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [15]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

Requirement already satisfied: palmerpenguins in /opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages (0.1.6)
Requirement already satisfied: pandas in /opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages (from palmerpenguins) (2.3.3)
Requirement already satisfied: numpy in /opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages (from palmerpenguins) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages (from pandas->palmerpenguins) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages (from pandas->palmerpenguins) (2026.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [16]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3750.0,39.1,18.7,181.0,False,True
1,3800.0,39.5,17.4,186.0,True,False
2,3250.0,40.3,18.0,195.0,True,False
3,NaN,NaN,NaN,NaN,False,False
4,3450.0,36.7,19.3,193.0,True,False
...,...,...,...,...,...,...
339,4000.0,55.8,19.8,207.0,False,True
340,3400.0,43.5,18.1,202.0,True,False
341,3775.0,49.6,18.2,193.0,False,True
342,4100.0,50.8,19.0,210.0,False,True
343,3775.0,50.2,18.7,198.0,True,False

In [17]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.291667,0.254545,0.666667,0.152542,0.0,1.0
1,0.305556,0.269091,0.511905,0.237288,1.0,0.0
2,0.152778,0.298182,0.583333,0.389831,1.0,0.0
3,NaN,NaN,NaN,NaN,0.0,0.0
4,0.208333,0.167273,0.738095,0.355932,1.0,0.0
...,...,...,...,...,...,...
339,0.361111,0.861818,0.797619,0.593220,0.0,1.0
340,0.194444,0.414545,0.595238,0.508475,1.0,0.0
341,0.298611,0.636364,0.607143,0.355932,0.0,1.0
342,0.388889,0.680000,0.702381,0.644068,0.0,1.0
343,0.298611,0.658182,0.666667,0.440678,1.0,0.0

In [18]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...
339    Chinstrap
340    Chinstrap
341    Chinstrap
342    Chinstrap
343    Chinstrap
Name: species, Length: 344, dtype: object

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [19]:
# Shuffle the data so all 3 species are mixed throughout
# Without this, the data is grouped by species (all Adelie first, then Gentoo, then Chinstrap)
# which causes the model to train poorly and produce nan loss values

penguins_combined = scaled_penguins_x.copy()
penguins_combined['target'] = penguins_y

# Drop rows with NaN values (2 rows in this dataset)
penguins_combined = penguins_combined.dropna()

# Shuffle with a fixed random_state so results are reproducible
penguins_combined = penguins_combined.sample(frac=1, random_state=42).reset_index(drop=True)

# Re-separate X and y after shuffle — both will now have 342 rows
scaled_penguins_x = penguins_combined.drop(columns=['target'])
penguins_y = penguins_combined['target'].values

print(f"Rows after shuffle and dropna: {scaled_penguins_x.shape[0]}")
print(f"Class distribution: {dict(zip(*[list(x) for x in __import__('numpy').unique(penguins_y, return_counts=True)]))}")
scaled_penguins_x.head()

Rows after shuffle and dropna: 342
Class distribution: {np.int8(0): np.int64(151), np.int8(1): np.int64(68), np.int8(2): np.int64(123)}

   body_mass_g  bill_length_mm  bill_depth_mm  flipper_length_mm  female  male
0     0.527778        0.410909       0.154762           0.779661     1.0   0.0
1     0.298611        0.189091       0.880952           0.457627     0.0   1.0
2     0.333333        0.272727       0.904762           0.322034     1.0   0.0
3     0.472222        0.436364       0.785714           0.406780     0.0   1.0
4     0.444444        0.341818       0.619048           0.389831     0.0   1.0

In [20]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='sigmoid')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [21]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
keras.utils.plot_model(model, show_shapes = True)

You must install graphviz (see instructions at https://graphviz.gitlab.io/download/) for `plot_model` to work.

In [23]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

/opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3583 - loss: 1.0743 - val_accuracy: 0.4000 - val_loss: 1.0754
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3616 - loss: 1.0623 - val_accuracy: 0.4000 - val_loss: 1.0654
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4007 - loss: 1.0543 - val_accuracy: 0.4286 - val_loss: 1.0569
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4495 - loss: 1.0472 - val_accuracy: 0.4286 - val_loss: 1.0485
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4463 - loss: 1.0403 - val_accuracy: 0.4286 - val_loss: 1.0407
Epoch 6/100

/opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4788 - loss: 1.0329 - val_accuracy: 0.4286 - val_loss: 1.0329
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4919 - loss: 1.0260 - val_accuracy: 0.4286 - val_loss: 1.0247
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4886 - loss: 1.0184 - val_accuracy: 0.4286 - val_loss: 1.0164
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5342 - loss: 1.0105 - val_accuracy: 0.4571 - val_loss: 1.0069
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5309 - loss: 1.0025 - val_accuracy: 0.4571 - val_loss: 0.9976
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5570 - loss: 0.9940 - val_accuracy: 0.4857 - val_loss: 0.9879
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5668 - loss: 0.9856 - val_accuracy: 0.5143 - val_loss: 0.9786
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6059 - loss: 0.9764 - val_accuracy: 0.5143 - val_loss: 0.9682
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6059 - loss: 0.9681 - val_accuracy: 0.5714 - val_loss: 0.9582
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6124 - loss: 0.9589 - val_accuracy: 0.6286 - val_loss: 0.9482
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6482 - loss: 0.9497 - val_accuracy: 0.6286 - val_loss: 0.9379
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6515 - loss: 0.9414 - val_accuracy: 0.6571 - val_loss: 0.9280
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6547 - loss: 0.9322 - val_accuracy: 0.6857 - val_loss: 0.9183
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6710 - loss: 0.9232 - val_accuracy: 0.7143 - val_loss: 0.9088
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6775 - loss: 0.9142 - val_accuracy: 0.7143 - val_loss: 0.8987
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6808 - loss: 0.9056 - val_accuracy: 0.7143 - val_loss: 0.8899
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6971 - loss: 0.8968 - val_accuracy: 0.7143 - val_loss: 0.8805
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7068 - loss: 0.8874 - val_accuracy: 0.7143 - val_loss: 0.8705
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7101 - loss: 0.8786 - val_accuracy: 0.7143 - val_loss: 0.8611
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7134 - loss: 0.8696 - val_accuracy: 0.8000 - val_loss: 0.8521
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7394 - loss: 0.8603 - val_accuracy: 0.7143 - val_loss: 0.8406
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7166 - loss: 0.8516 - val_accuracy: 0.7714 - val_loss: 0.8324
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.8429 - val_accuracy: 0.7714 - val_loss: 0.8224
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.8337 - val_accuracy: 0.7714 - val_loss: 0.8126
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.8250 - val_accuracy: 0.7429 - val_loss: 0.8028
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7296 - loss: 0.8169 - val_accuracy: 0.8000 - val_loss: 0.7955
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.8079 - val_accuracy: 0.8000 - val_loss: 0.7863
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.7996 - val_accuracy: 0.7714 - val_loss: 0.7768
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.7911 - val_accuracy: 0.8000 - val_loss: 0.7694
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.7832 - val_accuracy: 0.8000 - val_loss: 0.7594
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.7751 - val_accuracy: 0.8000 - val_loss: 0.7534
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.7670 - val_accuracy: 0.8000 - val_loss: 0.7432
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.7599 - val_accuracy: 0.8000 - val_loss: 0.7359
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.7522 - val_accuracy: 0.8000 - val_loss: 0.7273
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.7446 - val_accuracy: 0.8000 - val_loss: 0.7206
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.7378 - val_accuracy: 0.8000 - val_loss: 0.7125
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.7314 - val_accuracy: 0.8000 - val_loss: 0.7055
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7687 - loss: 0.7239 - val_accuracy: 0.8000 - val_loss: 0.6980
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.7177 - val_accuracy: 0.8000 - val_loss: 0.6908
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.7110 - val_accuracy: 0.8000 - val_loss: 0.6834
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.7044 - val_accuracy: 0.8000 - val_loss: 0.6760
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.6980 - val_accuracy: 0.8000 - val_loss: 0.6688
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.6925 - val_accuracy: 0.8000 - val_loss: 0.6632
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7752 - loss: 0.6865 - val_accuracy: 0.8000 - val_loss: 0.6570
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.6812 - val_accuracy: 0.8000 - val_loss: 0.6500
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.6755 - val_accuracy: 0.8000 - val_loss: 0.6445
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.6705 - val_accuracy: 0.8000 - val_loss: 0.6394
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.6653 - val_accuracy: 0.8000 - val_loss: 0.6336
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.6605 - val_accuracy: 0.8000 - val_loss: 0.6287
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.6558 - val_accuracy: 0.8000 - val_loss: 0.6229
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.6513 - val_accuracy: 0.8000 - val_loss: 0.6197
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.6472 - val_accuracy: 0.8000 - val_loss: 0.6143
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.6436 - val_accuracy: 0.8000 - val_loss: 0.6093
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.6396 - val_accuracy: 0.8000 - val_loss: 0.6075
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.6356 - val_accuracy: 0.8000 - val_loss: 0.6023
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.6320 - val_accuracy: 0.8000 - val_loss: 0.5990
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.6290 - val_accuracy: 0.8000 - val_loss: 0.5968
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.6255 - val_accuracy: 0.8000 - val_loss: 0.5941
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.6221 - val_accuracy: 0.8000 - val_loss: 0.5916
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.6189 - val_accuracy: 0.8000 - val_loss: 0.5876
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.6156 - val_accuracy: 0.8000 - val_loss: 0.5825
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.6128 - val_accuracy: 0.8000 - val_loss: 0.5811
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.6099 - val_accuracy: 0.8000 - val_loss: 0.5779
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.6074 - val_accuracy: 0.8000 - val_loss: 0.5768
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.6045 - val_accuracy: 0.8000 - val_loss: 0.5721
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.6020 - val_accuracy: 0.8000 - val_loss: 0.5706
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5996 - val_accuracy: 0.8000 - val_loss: 0.5672
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.5971 - val_accuracy: 0.8000 - val_loss: 0.5653
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5947 - val_accuracy: 0.8000 - val_loss: 0.5633
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5925 - val_accuracy: 0.8000 - val_loss: 0.5612
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.5905 - val_accuracy: 0.8000 - val_loss: 0.5605
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5886 - val_accuracy: 0.8000 - val_loss: 0.5569
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5865 - val_accuracy: 0.8000 - val_loss: 0.5560
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5844 - val_accuracy: 0.8000 - val_loss: 0.5527
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5825 - val_accuracy: 0.8000 - val_loss: 0.5510
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5807 - val_accuracy: 0.8000 - val_loss: 0.5496
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5789 - val_accuracy: 0.8000 - val_loss: 0.5470
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5771 - val_accuracy: 0.8000 - val_loss: 0.5458
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5754 - val_accuracy: 0.8000 - val_loss: 0.5441
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5740 - val_accuracy: 0.8000 - val_loss: 0.5425
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5720 - val_accuracy: 0.8000 - val_loss: 0.5407
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5705 - val_accuracy: 0.8000 - val_loss: 0.5390
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5688 - val_accuracy: 0.8000 - val_loss: 0.5377
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5674 - val_accuracy: 0.8000 - val_loss: 0.5364
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5659 - val_accuracy: 0.8000 - val_loss: 0.5353
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.5642 - val_accuracy: 0.8000 - val_loss: 0.5338
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8013 - loss: 0.5628 - val_accuracy: 0.8000 - val_loss: 0.5332
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.5611 - val_accuracy: 0.8000 - val_loss: 0.5315
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5597 - val_accuracy: 0.8000 - val_loss: 0.5304
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5582 - val_accuracy: 0.8000 - val_loss: 0.5291
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5567 - val_accuracy: 0.8000 - val_loss: 0.5275
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5555 - val_accuracy: 0.8000 - val_loss: 0.5266
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5539 - val_accuracy: 0.8000 - val_loss: 0.5251
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5525 - val_accuracy: 0.8000 - val_loss: 0.5235
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5511 - val_accuracy: 0.8000 - val_loss: 0.5229
11/11 - 0s - 1ms/step - accuracy: 0.8012 - loss: 0.5474

In [24]:
model_logit_true = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_true.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8013 - loss: 0.5493 - val_accuracy: 0.8000 - val_loss: 0.5199
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5467 - val_accuracy: 0.8000 - val_loss: 0.5181
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5450 - val_accuracy: 0.8000 - val_loss: 0.5169
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5435 - val_accuracy: 0.8000 - val_loss: 0.5154
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5421 - val_accuracy: 0.8000 - val_loss: 0.5138
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5410 - val_accuracy: 0.8000 - val_loss: 0.5128
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5396 - val_accuracy: 0.8000 - val_loss: 0.5120
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5384 - val_accuracy: 0.8000 - val_loss: 0.5105
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5372 - val_accuracy: 0.8000 - val_loss: 0.5096
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.5359 - val_accuracy: 0.8000 - val_loss: 0.5087
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5349 - val_accuracy: 0.8000 - val_loss: 0.5074
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5336 - val_accuracy: 0.8000 - val_loss: 0.5060
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5327 - val_accuracy: 0.8000 - val_loss: 0.5054
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5315 - val_accuracy: 0.8000 - val_loss: 0.5045
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5303 - val_accuracy: 0.8000 - val_loss: 0.5035
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5293 - val_accuracy: 0.8000 - val_loss: 0.5022
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5282 - val_accuracy: 0.8000 - val_loss: 0.5010
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5272 - val_accuracy: 0.8000 - val_loss: 0.5003
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5260 - val_accuracy: 0.8000 - val_loss: 0.4991
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5251 - val_accuracy: 0.8000 - val_loss: 0.4987
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5240 - val_accuracy: 0.8000 - val_loss: 0.4974
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5229 - val_accuracy: 0.8000 - val_loss: 0.4963
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5219 - val_accuracy: 0.8000 - val_loss: 0.4956
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5209 - val_accuracy: 0.8000 - val_loss: 0.4947
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5199 - val_accuracy: 0.8000 - val_loss: 0.4936
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5188 - val_accuracy: 0.8000 - val_loss: 0.4926
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5179 - val_accuracy: 0.8000 - val_loss: 0.4920
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5168 - val_accuracy: 0.8000 - val_loss: 0.4908
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5159 - val_accuracy: 0.8000 - val_loss: 0.4902
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.5149 - val_accuracy: 0.8000 - val_loss: 0.4892
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.5140 - val_accuracy: 0.8000 - val_loss: 0.4885
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5130 - val_accuracy: 0.8000 - val_loss: 0.4874
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5121 - val_accuracy: 0.8000 - val_loss: 0.4866
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.5111 - val_accuracy: 0.8000 - val_loss: 0.4859
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5102 - val_accuracy: 0.8000 - val_loss: 0.4849
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5094 - val_accuracy: 0.8000 - val_loss: 0.4842
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.5084 - val_accuracy: 0.8000 - val_loss: 0.4832
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5075 - val_accuracy: 0.8000 - val_loss: 0.4826
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5066 - val_accuracy: 0.8000 - val_loss: 0.4816
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5058 - val_accuracy: 0.8000 - val_loss: 0.4809
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5048 - val_accuracy: 0.8000 - val_loss: 0.4801
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5042 - val_accuracy: 0.8000 - val_loss: 0.4795
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5032 - val_accuracy: 0.8000 - val_loss: 0.4787
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5024 - val_accuracy: 0.8000 - val_loss: 0.4780
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5016 - val_accuracy: 0.8000 - val_loss: 0.4771
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5007 - val_accuracy: 0.8000 - val_loss: 0.4764
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4999 - val_accuracy: 0.8000 - val_loss: 0.4758
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4991 - val_accuracy: 0.8000 - val_loss: 0.4750
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4984 - val_accuracy: 0.8000 - val_loss: 0.4743
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4975 - val_accuracy: 0.8000 - val_loss: 0.4736
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4967 - val_accuracy: 0.8000 - val_loss: 0.4728
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4959 - val_accuracy: 0.8000 - val_loss: 0.4722
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4951 - val_accuracy: 0.8000 - val_loss: 0.4714
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4944 - val_accuracy: 0.8000 - val_loss: 0.4708
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4936 - val_accuracy: 0.8000 - val_loss: 0.4702
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4929 - val_accuracy: 0.8000 - val_loss: 0.4694
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4921 - val_accuracy: 0.8000 - val_loss: 0.4687
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4914 - val_accuracy: 0.8000 - val_loss: 0.4682
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4906 - val_accuracy: 0.8000 - val_loss: 0.4674
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4899 - val_accuracy: 0.8000 - val_loss: 0.4669
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4892 - val_accuracy: 0.8000 - val_loss: 0.4662
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4884 - val_accuracy: 0.8000 - val_loss: 0.4655
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4878 - val_accuracy: 0.8000 - val_loss: 0.4649
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4870 - val_accuracy: 0.8000 - val_loss: 0.4642
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4864 - val_accuracy: 0.8000 - val_loss: 0.4637
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4857 - val_accuracy: 0.8000 - val_loss: 0.4632
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4850 - val_accuracy: 0.8000 - val_loss: 0.4625
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4844 - val_accuracy: 0.8000 - val_loss: 0.4619
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4837 - val_accuracy: 0.8000 - val_loss: 0.4614
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4831 - val_accuracy: 0.8000 - val_loss: 0.4608
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4824 - val_accuracy: 0.8000 - val_loss: 0.4602
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4818 - val_accuracy: 0.8000 - val_loss: 0.4596
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4811 - val_accuracy: 0.8000 - val_loss: 0.4590
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4805 - val_accuracy: 0.8000 - val_loss: 0.4585
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4799 - val_accuracy: 0.8000 - val_loss: 0.4580
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4792 - val_accuracy: 0.8000 - val_loss: 0.4574
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4786 - val_accuracy: 0.8000 - val_loss: 0.4569
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4780 - val_accuracy: 0.8000 - val_loss: 0.4563
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4774 - val_accuracy: 0.8000 - val_loss: 0.4558
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4768 - val_accuracy: 0.8000 - val_loss: 0.4553
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4762 - val_accuracy: 0.8000 - val_loss: 0.4547
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4758 - val_accuracy: 0.8000 - val_loss: 0.4543
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4751 - val_accuracy: 0.8000 - val_loss: 0.4538
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4746 - val_accuracy: 0.8000 - val_loss: 0.4532
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4740 - val_accuracy: 0.8000 - val_loss: 0.4528
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4735 - val_accuracy: 0.8000 - val_loss: 0.4523
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4729 - val_accuracy: 0.8000 - val_loss: 0.4518
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4724 - val_accuracy: 0.8000 - val_loss: 0.4514
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4719 - val_accuracy: 0.8000 - val_loss: 0.4509
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4713 - val_accuracy: 0.8000 - val_loss: 0.4504
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4708 - val_accuracy: 0.8000 - val_loss: 0.4500
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8013 - loss: 0.4702 - val_accuracy: 0.8000 - val_loss: 0.4495
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4697 - val_accuracy: 0.8000 - val_loss: 0.4490
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4691 - val_accuracy: 0.8000 - val_loss: 0.4485
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4686 - val_accuracy: 0.8000 - val_loss: 0.4480
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4680 - val_accuracy: 0.8000 - val_loss: 0.4475
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4675 - val_accuracy: 0.8000 - val_loss: 0.4470
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4669 - val_accuracy: 0.8000 - val_loss: 0.4465
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4665 - val_accuracy: 0.8000 - val_loss: 0.4461
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4659 - val_accuracy: 0.8000 - val_loss: 0.4456
11/11 - 0s - 1ms/step - accuracy: 0.8012 - loss: 0.4635

In [25]:
model_logit_true.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[0.02284109, 0.02593094, 0.99967754],
       [0.70838207, 0.5173977 , 0.27782777],
       [0.70838207, 0.5173977 , 0.27782777],
       ...,
       [0.70838207, 0.5173977 , 0.27782777],
       [0.01586582, 0.0197293 , 0.99984   ],
       [0.70838207, 0.5173977 , 0.27782783]],
      shape=(342, 3), dtype=float32)

In [26]:
penguins['species']

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...
339    Chinstrap
340    Chinstrap
341    Chinstrap
342    Chinstrap
343    Chinstrap
Name: species, Length: 344, dtype: object

In [ ]:
penguins_y

array([2, 0, 0, 0, 0, 1, 2, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 0, 2, 0, 2, 0,
       1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 0, 2, 2,
       0, 2, 1, 2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 1, 1, 0, 2, 1, 1, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 2, 1, 0, 0, 2, 0, 1, 0, 0, 0, 1,
       0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 1, 2,
       0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 1, 0, 2, 1, 2, 2,
       2, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1,
       1, 1, 2, 2, 1, 1, 2, 2, 0, 0, 1, 2, 2, 0, 1, 2, 0, 1, 1, 2, 1, 2,
       2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 2,
       2, 0, 1, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 2,
       0, 0, 0, 2, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 2, 2, 0,
       2, 0, 0, 2, 0, 0, 2, 0, 0, 1, 0, 1, 2, 1, 0, 1, 2, 2, 1, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 0, 2,
       2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 2,
       0, 0, 2, 2, 1, 2, 2, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 2, 1, 0, 0, 2,
       0, 0, 1, 2, 0, 1, 0, 2, 0, 0, 2, 0], dtype=int8)